### ISSUE TITLE
Roadmap to v0.1

### ISSUE THREAD

**Issue by egregors** [logux/django#1]
This package should be minimalist idiomatic Django [reusable app](https://docs.djangoproject.com/en/2.2/intro/reusable-apps/) to integrate Logux.

#### Requirements: 
* Django >= 2.2.12
* Python >= 3.7

#### Todo's:

- [x] discover `LOGUX_URL` and `LOGUX_CONTROL_PASSWORD` in consumer `settings.py` or ENV

- [x]  expect in the settings `LoguxAuthentication` class with single method `is_auth(user_id, token: str) -> bool`  and provide the base implementation for internal Django `AuthenticationMiddleware`
    - [x]  **auth through `django.contrib.auth.login` or just comparing password in actions with LOGUX_CONTROL_PASSWORD?**

- [x] add function to send `LoguxAction` to the Logux Proxy: 
```
logux_add(action: LoguxAction, meta: Optional[LoguxMeta]) -> None
```

- [x] add Meta class for `LoguxAction` with 3 requared metods:
```
resend(self, meta: Optional[LoguxMeta]) -> LoguxAction
access(self, meta: Optional[LoguxMeta]) -> bool
process(self, meta: Optional[LoguxMeta]) -> None
```
- [x] all consumer `LoguxAction`s should be in `logux_actions.py`. 
  - [x] actions in `module_name.logux_actions.py` per each module? More pythonic way, but then we need auto-discovery for action files. 

- [x] API for channel subscription 
  - [x] subscription parser for  smth like `users/:id`
  - [x] subscription methods
  ```
    access(action: LoguxAction, meta: Optional[LoguxMeta]) -> boolean
    init(action: LoguxAction, meta: Optional[LoguxMeta]) -> None  
  ```

- [x] actions and subscriptions helpers like [JS API](https://logux.io/node-api/#context). `meta.id` parsing into `userId` and `clientId`. Client version checker. Etc.

- [x] add `send_back(action: LoguxAction, meta: Optional[LoguxMeta]) -> None` function. Don't really got, what it exactly means 🤷‍♀️🤷‍♀️🤷‍♀️

- [x] Makefile: install, run, lint, test
- [x] test app
- [x] README with quick start and examples 
- [x] publish to PyPI
- [x] setup GitHub Actions (or another CI) to lint, test, build and publish pkg

**Comment by ai** [comment]
> auth through django.contrib.auth.login or just comparing password in actions with LOGUX_CONTROL_PASSWORD?

`LOGUX_CONTROL_PASSWORD` is to authenticate the Logux Server or back-end server in their internal communication (to prevent sending `/logux` requests from outside of the local network if admin forgot to setup firewall).

`LoguxAuthentication` authenticates users.

Token for `LoguxAuthentication` must be stored by the client in localStorage. It is insecure storage for a password. Here how I see the auth process in Logux:

1. The user opens the auth popup.
2. The user enters email and password (or use WebAuthn).
3. Popup sends HTTP-request with credentials to back-end without Logux.
4. The back-end generates a token and sends it back to the client.
5. The client saves the token to localStorage and uses it to establish a Logux connection.

So, Logux will not use real passwords for user’s auth.

**Comment by ai** [comment]
> Is Logux Proxy always be near the backend server?

In the future, we have an idea of “Logux Proxy as a Service”

> maybe async (probably redundant, because 2.2 does not support @sync_to_async).

Great idea for the next release. Especially, if the async feature is not stable yet

**Comment by ai** [comment]
> resend(self, meta: Optional[LoguxMeta]) -> LoguxAction

`resend` returns an object https://logux.io/node-api/#resend

This object is not action. Technically, this object contains some keys for `meta`: `channels`, `channel`, 'users', 'user`, … (all `meta` keys which affect on what clients will receive new action).

**Comment by ai** [comment]
> actions in module_name.logux_actions.py per each module? More pythonic way, but then we need auto-discovery for action files.

I think we need to split processing per module. We could have 10-30 different actions per project.

**Comment by ai** [comment]
>  add send_back(). Don't really got, what it exactly means

Here is an example: https://logux.io/node-api/#server-channel

`send_back` is just syntax sugar. It is a wrapper for `logux_add`. Often in action’s response, you need to send action back to the client.

```js
// meta.clients tells server to send action to the client with this client ID
function send_back (action, meta) {
  logux_add(action, { ...meta, client: originMeta.clientId })
}
```

**Comment by ai** [comment]
Extra tasks for docs:

1. Ideally, we need API page like https://logux.io/node-api (but it will be better to move it to release 2 since we need to to have a custom design on API page)
2. We will need to add docs to [`logux/docs`](https://github.com/logux/docs). My current idea, that project’s `README.md` contains the simplest example and all docs will be on [logux.io](https://logux.io/).

**Comment by egregors** [comment]
🎉 🎉 🎉
